### ISSUE TITLE
Unreachable Backend For All Server Requests

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/nudge-webapp#11]
Commit #10 solved this issue for the login and register pages, however we should include the code used in that commit any time we attempt to reach the backend.

**Comment by torch2424** [comment]
I updated the code to catch all errors, instead of just unreachable servers, however, it's hard to tell when you are requesting for a server without the comments yo

**Comment by torch2424** [comment]
Wait I found em

**Comment by torch2424** [comment]
Alright, so I added the function to the go function. And all this funception you got going on is messing with me haha! I didn't add it to the cookie function since its local and not back end. And I didn't add it to the services, since after an hour of research, I heard it might increase the overhead, which I remember you saying is something you Dont want to do

**Comment by torch2424** [comment]
Oh, and does every $scope. Pass a response or no?

**Comment by julianpoy** [comment]
I'm going to try and address everything you said here, but I apologize ahead of time if I miss something.

First off, I think I commented everything in a previous commit as part of the code cleanup branch. This can be part of your local repository with git pull or if you want to take a look at it through the web interface that works as well.

That should show you where each request is being made, and should pave the way for you to understand how AngularJS and JavaScript server requests work.

The "go" function is something simply for switching the URL of the browser instead of using links. Because AngularJS downloads the entire site on the first page load, using links requires the site to be reloaded unnecessarily which slows down browse speeds. With the "go" function, we can switch URLs without page reloads, and therefore have it be instant like a native application. The "go" function has nothing to do with server requests.

On the same type of topic: $scope. Although I don't fully understand $scope, the way I have had it explained to me is its basically the separation between pages. The $scope is something that is accessible inside of the scope of the current page. Its accessible from the HTML as well. Since AngularJS is really only a single page as explained before, $scope separates one page from the other, by having a local variable space.

I hope that clears things up. I'll show you how to insert the code for the functions tomorrow.

**Comment by torch2424** [comment]
Julian, you have no clue how much this paragraph helped me. This was better thanything I could find after 2 hours of looking <3

**Comment by torch2424** [comment]
But fashow, We'll figure it out tommorow!
