### ISSUE TITLE
New RSVP'd events page

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/nudge-webapp#18]
Currently the "RSVP'd" button on
http://localhost:9000/#/events
is directed towards the URL
http://localhost:9000/#/events/rsvp

At that URL there should exist a page that lists out all of the events that the user has RSVP'd to as well as a section for pending RSVPs.

**Comment by torch2424** [comment]
In the event page branch

**Comment by torch2424** [comment]
closed via #58

**Comment by torch2424** [comment]
closed via #58
