### ISSUE TITLE
Close the triple bar mobile menu upon action

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/nudge-webapp#19]
Currently the triple bar mobile menu stays open after you use it to navigate to another page. This chops off a portion of the page and looks scrappy. It should hide itself after navigation has occurred.

**Comment by torch2424** [comment]
I think I can do this!

**Comment by julianpoy** [comment]
Awesome

**Comment by torch2424** [comment]
JUST DID THIS AWWWEEEEEE YEAH!!!!! It was way harder than I thought it'd be, but I'm gonna comment and push my stuff now

**Comment by torch2424** [comment]
Actually, I'm REALLLYYYY close! my javascript works perfect, so I'm stoked on that, I just need your help with the ng-hide/show stuff on friday sound good? you can look at my commits in the branch close bar if you want a sneak peek at what I was doing

**Comment by torch2424** [comment]
@julianpoy

**Comment by torch2424** [comment]
Fixed via #43

**Comment by torch2424** [comment]
Fixed via #43
