### ISSUE TITLE
Need to be able to unfriend people

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/nudge-webapp#38]
I know this sounds sad, but peeps need to be able to delete those friends.

**Comment by torch2424** [comment]
Yeah I dont like ejkj, I heard he's talking about mad crap us

**Comment by julianpoy** [comment]
Hahaha

**Comment by torch2424** [comment]
Need to create template for ngDialog, simply place under views/alerts for template htmls

**Comment by torch2424** [comment]
Closed via #56
