### ISSUE TITLE
Private/Public event radio button doesn't work

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/nudge-webapp#46]
There is no effect when selecting the public/private radio button. The event will be private nomatter what.

**Comment by torch2424** [comment]
I can fix this! Is the backend ready for it?

**Comment by julianpoy** [comment]
The backend is intact ready for it. The backend wants 0 for private and 1 for public. I think the problem is that the frontend is currently sending "public" and "private" to the backend, which gets discarded and defaults to 0. Throw 0 or 1 at the backend and it should work just dandy.

**Comment by torch2424** [comment]
Alright awesome! I'll get on this when I can!

**Comment by torch2424** [comment]
Closed via #55
