### ISSUE TITLE
Edit Event Page

### ISSUE THREAD

**Issue by julianpoy** [Kondeo/nudge-webapp#51]
Page to edit events for hosts.

**Comment by torch2424** [comment]
Backend is not built for this yet :'(

**Comment by torch2424** [comment]
It is now built, I'm doing this!

**Comment by torch2424** [comment]
Waiting for backend to support date formatting on return

**Comment by torch2424** [comment]
Julian fixed it <3

**Comment by torch2424** [comment]
Closed via #61
